# Generated by Django 4.1.4 on 2023-02-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Requestor', models.TextField()),
                ('Beneficiary', models.TextField()),
                ('AssetNumber', models.TextField()),
                ('Category', models.TextField()),
                ('Comment', models.TextField()),
            ],
        ),
    ]
